"""Export DenseCfC checkpoints as firmware C headers.

The head output dimension is taken from ``head.weight`` in each checkpoint so
the generated firmware header always matches the deployed model.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np
import torch

PROJECT_ROOT = Path(__file__).resolve().parents[2]
FIRMWARE_MAIN_DIR = PROJECT_ROOT / "firmware" / "main"

# Fixed DenseCfC backbone layers.  The checkpoint head is intentionally not
# listed here because its output dimension is deployment-specific.
LAYER_SPEC = (
    ("backbone", "cfc.rnn_cell.backbone.0", 268, 128),
    ("ff1", "cfc.rnn_cell.ff1", 128, 256),
    ("ff2", "cfc.rnn_cell.ff2", 128, 256),
    ("time_a", "cfc.rnn_cell.time_a", 128, 256),
    ("time_b", "cfc.rnn_cell.time_b", 128, 256),
    ("head", "head", 256, 5),  # Legacy fixture/default; export infers this value.
)

INPUT_DIM = 12
HIDDEN_DIM = 256
BACKBONE_UNITS = 128


def quantize_per_channel(weight: torch.Tensor) -> tuple[torch.Tensor, np.ndarray]:
    """Quantize one linear layer with one symmetric scale per output row."""
    weight = weight.detach().float()
    maximum = weight.abs().max(dim=1).values
    maximum = torch.where(maximum < 1e-10, torch.ones_like(maximum), maximum)
    scales = (maximum / 127.0).numpy().astype(np.float32)
    quantized = torch.clamp(
        torch.round(weight / torch.from_numpy(scales).unsqueeze(1)), -127, 127
    ).to(torch.int8)
    return quantized, scales


def compute_error(weight: torch.Tensor, quantized: torch.Tensor, scales: np.ndarray) -> float:
    """Return maximum reconstruction error relative to the tensor range."""
    reconstructed = quantized.float() * torch.from_numpy(scales).unsqueeze(1)
    maximum_error = (weight.detach().float() - reconstructed).abs().max().item()
    value_range = weight.max().item() - weight.min().item()
    return float(maximum_error / (value_range + 1e-8) * 100.0)


def _array_literal(data: np.ndarray, fmt: str, per_line: int = 8) -> str:
    flat = data.ravel()
    rows = [
        "    " + ", ".join(fmt.format(value) for value in flat[index : index + per_line]) + ","
        for index in range(0, len(flat), per_line)
    ]
    return "{\n" + "\n".join(rows) + "\n}"


def output_dim_from_state_dict(state_dict: dict[str, torch.Tensor]) -> int:
    """Read the deployed output dimension from the checkpoint head weight."""
    try:
        head_weight = state_dict["head.weight"]
        head_bias = state_dict["head.bias"]
    except KeyError as error:
        raise ValueError("checkpoint is missing the DenseCfC head weights") from error

    if head_weight.ndim != 2 or head_weight.shape[1] != HIDDEN_DIM:
        raise ValueError(
            "head.weight must have shape (output_dim, "
            f"{HIDDEN_DIM}), got {list(head_weight.shape)}"
        )
    output_dim = int(head_weight.shape[0])
    if output_dim < 1 or tuple(head_bias.shape) != (output_dim,):
        raise ValueError(
            "head.bias must have shape "
            f"({output_dim},), got {list(head_bias.shape)}"
        )
    return output_dim


def _export_layers(output_dim: int) -> tuple[tuple[str, str, int, int], ...]:
    return (*LAYER_SPEC[:-1], ("head", "head", HIDDEN_DIM, output_dim))


def validate_target_contract(checkpoint: dict[str, Any], output_dim: int) -> None:
    contract = checkpoint.get("target_contract")
    if contract is None:
        return
    if not isinstance(contract, dict):
        raise TypeError("checkpoint target_contract must be a dictionary")
    if int(contract.get("output_dim", -1)) != output_dim:
        raise ValueError("checkpoint target_contract output_dim disagrees with head.weight")
    target_names = contract.get("target_names")
    if target_names is not None and len(target_names) != output_dim:
        raise ValueError("checkpoint target_contract target_names width is inconsistent")


def generate_weights_h(state_dict: dict[str, torch.Tensor]) -> str:
    """Generate ``weights.h`` with dimensions consistent with the checkpoint."""
    output_dim = output_dim_from_state_dict(state_dict)
    lines = [
        "// Auto-generated by export_weights.py — do not edit by hand.",
        "// DenseCfC RMS-only per-channel INT8 weights.",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "// ── Dimension constants ──────────────────────────────",
        f"#define CFC_INPUT_DIM      {INPUT_DIM}",
        f"#define CFC_HIDDEN_DIM     {HIDDEN_DIM}",
        f"#define CFC_OUTPUT_DIM     {output_dim}",
        f"#define CFC_BACKBONE_UNITS {BACKBONE_UNITS}",
        f"#define CFC_BACKBONE_IN    (CFC_INPUT_DIM + CFC_HIDDEN_DIM)  // {INPUT_DIM + HIDDEN_DIM}",
        "",
    ]
    errors: dict[str, float] = {}

    for name, state_key, input_dim, layer_output_dim in _export_layers(output_dim):
        weight_key = f"{state_key}.weight"
        bias_key = f"{state_key}.bias"
        try:
            weight = state_dict[weight_key]
            bias = state_dict[bias_key]
        except KeyError as error:
            raise ValueError(f"checkpoint is missing {name} layer parameters") from error
        if tuple(weight.shape) != (layer_output_dim, input_dim):
            raise ValueError(
                f"{name}.weight must have shape ({layer_output_dim}, {input_dim}), "
                f"got {list(weight.shape)}"
            )
        if tuple(bias.shape) != (layer_output_dim,):
            raise ValueError(
                f"{name}.bias must have shape ({layer_output_dim},), got {list(bias.shape)}"
            )

        quantized, scales = quantize_per_channel(weight)
        errors[name] = compute_error(weight, quantized, scales)
        lines.extend(
            [
                f"// ── {name}: Linear({input_dim} → {layer_output_dim})",
                f"static const int8_t cfc_{name}_weight[{layer_output_dim} * {input_dim}] =",
                _array_literal(quantized.numpy(), "{:d}"),
                ";",
                f"static const float cfc_{name}_weight_scale[{layer_output_dim}] =",
                _array_literal(scales, "{:.8f}f"),
                ";",
                f"static const float cfc_{name}_bias[{layer_output_dim}] =",
                _array_literal(bias.detach().float().numpy(), "{:.8f}f"),
                ";",
                "",
            ]
        )

    lines.append("// ── Per-layer reconstruction error ──────────────────")
    lines.extend(f"//   {name:12s} : {error:.4f}%" for name, error in errors.items())
    lines.append("")
    return "\n".join(lines)


def generate_normalization_h(
    center: np.ndarray,
    scale: np.ndarray,
    mu: float,
    *,
    target_center: np.ndarray,
    target_scale: np.ndarray,
    target_mu: float,
    output_dim: int,
) -> str:
    if center.shape != (INPUT_DIM,) or scale.shape != (INPUT_DIM,):
        raise ValueError(f"normalization center and scale must each contain {INPUT_DIM} values")
    if target_center.shape != (output_dim,) or target_scale.shape != (output_dim,):
        raise ValueError(
            "target normalization center and scale must each contain "
            f"{output_dim} values"
        )
    if not np.isfinite(mu) or mu <= 0.0:
        raise ValueError("feature normalization mu must be positive and finite")
    if not np.isfinite(target_mu) or target_mu <= 0.0:
        raise ValueError("target normalization mu must be positive and finite")
    if not np.all(np.isfinite(center)) or not np.all(np.isfinite(scale)):
        raise ValueError("feature normalization center and scale must be finite")
    if not np.all(np.isfinite(target_center)) or not np.all(np.isfinite(target_scale)):
        raise ValueError("target normalization center and scale must be finite")
    if np.any(scale <= 0.0) or np.any(target_scale <= 0.0):
        raise ValueError("normalization scales must be positive")
    return "\n".join(
        [
            "// Auto-generated by export_weights.py — do not edit by hand.",
            "#pragma once",
            f"#define MU_LAW_FEATURE_DIM  {INPUT_DIM}",
            f"#define MU_LAW_MU           {mu:.1f}f",
            f"static const float mu_law_center[{INPUT_DIM}] =",
            _array_literal(center.astype(np.float32), "{:.8f}f"),
            ";",
            f"static const float mu_law_scale[{INPUT_DIM}] =",
            _array_literal(scale.astype(np.float32), "{:.8f}f"),
            ";",
            "",
            "#define TARGET_NORMALIZATION_AVAILABLE 1",
            f"#define TARGET_MU_LAW_DIM              {output_dim}",
            f"#define TARGET_MU_LAW_MU               {target_mu:.1f}f",
            f"static const float target_mu_law_center[{output_dim}] =",
            _array_literal(target_center.astype(np.float32), "{:.8f}f"),
            ";",
            f"static const float target_mu_law_scale[{output_dim}] =",
            _array_literal(target_scale.astype(np.float32), "{:.8f}f"),
            ";",
            "",
        ]
    )


def _resolve_target_normalization(
    checkpoint: dict[str, Any],
    *,
    output_dim: int,
    target_center: np.ndarray | None,
    target_scale: np.ndarray | None,
    target_mu: float | None,
) -> tuple[np.ndarray, np.ndarray, float]:
    checkpoint_stats = checkpoint.get("target_normalization_stats")
    explicit_values = (target_center, target_scale, target_mu)
    if any(value is not None for value in explicit_values):
        if not all(value is not None for value in explicit_values):
            raise ValueError(
                "target normalization requires center, scale, and mu together"
            )
        resolved = (
            np.asarray(target_center, dtype=np.float32),
            np.asarray(target_scale, dtype=np.float32),
            float(target_mu),
        )
        if checkpoint_stats is not None:
            _validate_stats_match(
                checkpoint_stats,
                center=resolved[0],
                scale=resolved[1],
                mu=resolved[2],
                value_name="target",
            )
        return resolved

    stats = checkpoint_stats
    if stats is None:
        raise ValueError(
            "target normalization stats are required to export real-angle firmware outputs"
        )
    if not isinstance(stats, dict):
        raise TypeError("checkpoint target_normalization_stats must be a dictionary")
    if stats.get("method") != "mu_law":
        raise ValueError("firmware export requires mu-law target normalization")
    try:
        resolved_center = np.asarray(stats["center"], dtype=np.float32)
        resolved_scale = np.asarray(stats["scale"], dtype=np.float32)
        resolved_mu = float(stats["mu"])
    except KeyError as error:
        raise ValueError("checkpoint target normalization stats are incomplete") from error
    if resolved_center.shape != (output_dim,) or resolved_scale.shape != (output_dim,):
        raise ValueError(
            "checkpoint target normalization width must match head output_dim="
            f"{output_dim}"
        )
    return resolved_center, resolved_scale, resolved_mu


def _validate_stats_match(
    checkpoint_stats: Any,
    *,
    center: np.ndarray,
    scale: np.ndarray,
    mu: float,
    value_name: str,
) -> None:
    if not isinstance(checkpoint_stats, dict):
        raise TypeError(f"checkpoint {value_name}_normalization_stats must be a dictionary")
    if checkpoint_stats.get("method") != "mu_law":
        raise ValueError(f"checkpoint {value_name} normalization must use mu-law")
    try:
        expected_center = np.asarray(checkpoint_stats["center"], dtype=np.float32)
        expected_scale = np.asarray(checkpoint_stats["scale"], dtype=np.float32)
        expected_mu = float(checkpoint_stats["mu"])
    except KeyError as error:
        raise ValueError(
            f"checkpoint {value_name} normalization stats are incomplete"
        ) from error
    matches = (
        expected_center.shape == center.shape
        and expected_scale.shape == scale.shape
        and np.allclose(expected_center, center, rtol=1e-6, atol=1e-7)
        and np.allclose(expected_scale, scale, rtol=1e-6, atol=1e-7)
        and np.isclose(expected_mu, mu, rtol=1e-7, atol=0.0)
    )
    if not matches:
        raise ValueError(
            f"external {value_name} normalization stats disagree with checkpoint"
        )


def run_export(
    *,
    checkpoint_path: Path,
    output_dir: Path,
    norm_center: np.ndarray | None = None,
    norm_scale: np.ndarray | None = None,
    norm_mu: float = 255.0,
    target_center: np.ndarray | None = None,
    target_scale: np.ndarray | None = None,
    target_mu: float | None = None,
) -> dict[str, Any]:
    """Export a checkpoint after validating its required normalization stats."""
    if norm_center is None or norm_scale is None:
        raise ValueError("training normalization stats are required for firmware export")

    checkpoint = torch.load(str(checkpoint_path), map_location="cpu", weights_only=False)
    state_dict = checkpoint["model_state_dict"]
    output_dim = output_dim_from_state_dict(state_dict)
    validate_target_contract(checkpoint, output_dim)
    feature_center = np.asarray(norm_center, dtype=np.float32)
    feature_scale = np.asarray(norm_scale, dtype=np.float32)
    if feature_center.shape != (INPUT_DIM,) or feature_scale.shape != (INPUT_DIM,):
        raise ValueError(f"normalization center and scale must each contain {INPUT_DIM} values")
    checkpoint_feature_stats = checkpoint.get("feature_normalization_stats")
    if checkpoint_feature_stats is not None:
        _validate_stats_match(
            checkpoint_feature_stats,
            center=feature_center,
            scale=feature_scale,
            mu=float(norm_mu),
            value_name="feature",
        )
    resolved_target_center, resolved_target_scale, resolved_target_mu = (
        _resolve_target_normalization(
            checkpoint,
            output_dim=output_dim,
            target_center=target_center,
            target_scale=target_scale,
            target_mu=target_mu,
        )
    )
    weights_header = generate_weights_h(state_dict)
    normalization_header = generate_normalization_h(
        feature_center,
        feature_scale,
        float(norm_mu),
        target_center=resolved_target_center,
        target_scale=resolved_target_scale,
        target_mu=resolved_target_mu,
        output_dim=output_dim,
    )

    output_dir.mkdir(parents=True, exist_ok=True)
    weights_path = output_dir / "weights.h"
    normalization_path = output_dir / "normalization.h"
    weights_path.write_text(weights_header, encoding="utf-8")
    normalization_path.write_text(normalization_header, encoding="utf-8")
    return {
        "checkpoint": str(checkpoint_path),
        "weights_h": str(weights_path),
        "normalization_h": str(normalization_path),
        "output_dim": output_dim,
        "output_units": "joint_angle_original_scale",
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Export DenseCfC weights as firmware headers")
    parser.add_argument("--checkpoint", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, default=FIRMWARE_MAIN_DIR)
    parser.add_argument("--norm-stats", type=Path, required=True)
    args = parser.parse_args(argv)
    stats = np.load(str(args.norm_stats))
    report = run_export(
        checkpoint_path=args.checkpoint,
        output_dir=args.output_dir,
        norm_center=stats["center"],
        norm_scale=stats["scale"],
        norm_mu=float(stats.get("mu", 255.0)),
        target_center=stats.get("target_center"),
        target_scale=stats.get("target_scale"),
        target_mu=(
            float(stats["target_mu"])
            if "target_mu" in stats
            else None
        ),
    )
    print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
