"""Export DenseCfC weights as per-channel INT8 C header files.

Generates ``weights.h`` with quantized weight arrays, per-channel scales,
FP32 biases, and dimension macros.  Also generates ``normalization.h`` with
mu-law center/scale/mu constants for the C inference pipeline.

Usage::

    python -m src.hardwareOperation.export_weights \\
        --checkpoint log/.../S1_dense_cfc_head_ft.pt \\
        --output-dir src/hardwareOperation
"""

from __future__ import annotations

import argparse
import json
import sys
import types
from pathlib import Path
from typing import Any

import numpy as np
import torch

# ── Python 3.14 compatibility ───────────────────────────────────────────────
import pathlib as _pathlib

if "pathlib._local" not in sys.modules:
    _mock = types.ModuleType("pathlib._local")
    _mock.WindowsPath = _pathlib.WindowsPath
    _mock.PosixPath = _pathlib.PosixPath
    _mock.PureWindowsPath = _pathlib.PureWindowsPath
    _mock.PurePosixPath = _pathlib.PurePosixPath
    sys.modules["pathlib._local"] = _mock
# ────────────────────────────────────────────────────────────────────────────

PROJECT_ROOT = Path(__file__).resolve().parents[2]

# ── Layer metadata ──────────────────────────────────────────────────────────
# (c_name, state_dict_key, in_features, out_features)
LAYER_SPEC = [
    ("backbone", "cfc.rnn_cell.backbone.0", 268, 128),
    ("ff1",      "cfc.rnn_cell.ff1",        128, 256),
    ("ff2",      "cfc.rnn_cell.ff2",        128, 256),
    ("time_a",   "cfc.rnn_cell.time_a",     128, 256),
    ("time_b",   "cfc.rnn_cell.time_b",     128, 256),
    ("head",     "head",                    256,   5),
]

# Dimension constants (derived from layer spec)
INPUT_DIM = 12   # RMS-only over 12 channels
HIDDEN_DIM = 256
OUTPUT_DIM = 5
BACKBONE_UNITS = 128

# ── Quantization ────────────────────────────────────────────────────────────


def quantize_per_channel(weight: torch.Tensor) -> tuple[torch.Tensor, np.ndarray]:
    """Per-channel asymmetric INT8 quantization.

    Returns (q_int8, scales) where scales has shape (out_channels,).
    """
    w = weight.detach().float()
    w_max = w.abs().max(dim=1).values  # (out_channels,)
    w_max = torch.where(w_max < 1e-10, torch.ones_like(w_max), w_max)
    scales = (2.0 * w_max / 255.0).numpy().astype(np.float32)
    scale_bc = torch.from_numpy(scales).unsqueeze(1)  # (out, 1)
    q = torch.clamp(torch.round(w / scale_bc), -128, 127).to(torch.int8)
    return q, scales


def compute_error(original: torch.Tensor, q: torch.Tensor, scales: np.ndarray) -> float:
    """Relative reconstruction error (percent)."""
    recon = q.float() * torch.from_numpy(scales).unsqueeze(1)
    diff = (original.float() - recon).abs()
    max_err = diff.max().item()
    f_range = original.max().item() - original.min().item()
    return float(max_err / (f_range + 1e-8) * 100)


# ── C header generation ─────────────────────────────────────────────────────


def _array_literal(data: np.ndarray, fmt: str = "{}", per_line: int = 8) -> str:
    """Format a flat numpy array as a C initializer list."""
    flat = data.ravel()
    lines: list[str] = []
    for i in range(0, len(flat), per_line):
        chunk = flat[i : i + per_line]
        lines.append("    " + ", ".join(fmt.format(v) for v in chunk) + ",")
    joined = "\n".join(lines)
    return f"{{\n{joined}\n}}"


def generate_weights_h(state_dict: dict[str, torch.Tensor]) -> str:
    """Generate weights.h content."""
    lines: list[str] = []
    lines.append("// Auto-generated by export_weights.py — do not edit by hand.")
    lines.append("// DenseCfC h=256 RMS-only per-channel asymmetric INT8 weights.")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("// ── Dimension constants ──────────────────────────────")
    lines.append(f"#define CFC_INPUT_DIM      {INPUT_DIM}")
    lines.append(f"#define CFC_HIDDEN_DIM     {HIDDEN_DIM}")
    lines.append(f"#define CFC_OUTPUT_DIM     {OUTPUT_DIM}")
    lines.append(f"#define CFC_BACKBONE_UNITS  {BACKBONE_UNITS}")
    lines.append(f"#define CFC_BACKBONE_IN     (CFC_INPUT_DIM + CFC_HIDDEN_DIM)  // {INPUT_DIM + HIDDEN_DIM}")
    lines.append("")

    error_summary: dict[str, float] = {}

    for c_name, sd_key, in_dim, out_dim in LAYER_SPEC:
        w_key = f"{sd_key}.weight"
        b_key = f"{sd_key}.bias"
        weight = state_dict[w_key]
        bias = state_dict[b_key]
        assert weight.shape == (out_dim, in_dim), f"{c_name} weight: expected ({out_dim},{in_dim}), got {list(weight.shape)}"
        assert bias.shape == (out_dim,), f"{c_name} bias: expected ({out_dim},), got {list(bias.shape)}"

        q_w, scales = quantize_per_channel(weight)
        err = compute_error(weight, q_w, scales)
        error_summary[c_name] = err

        # Comment block
        lines.append(f"// ── {c_name}: Linear({in_dim} → {out_dim}) — {out_dim * in_dim:,} weights, {out_dim} biases")
        lines.append(f"// Reconstruction error: {err:.4f}%")

        # Weights (row-major: weight[row][col], row=output, col=input)
        w_flat = q_w.numpy().ravel()
        lines.append(f"static const int8_t cfc_{c_name}_weight[{out_dim} * {in_dim}] =")
        lines.append(_array_literal(w_flat, fmt="{:d}"))
        lines.append(";")
        lines.append("")

        # Per-channel scales
        lines.append(f"static const float cfc_{c_name}_weight_scale[{out_dim}] =")
        lines.append(_array_literal(scales, fmt="{:.8f}f"))
        lines.append(";")
        lines.append("")

        # Biases (FP32)
        b_flat = bias.detach().float().numpy().ravel()
        lines.append(f"static const float cfc_{c_name}_bias[{out_dim}] =")
        lines.append(_array_literal(b_flat, fmt="{:.8f}f"))
        lines.append(";")
        lines.append("")

    # Error summary
    lines.append("// ── Per-layer reconstruction error ──────────────────")
    for c_name, err in error_summary.items():
        lines.append(f"//   {c_name:12s} : {err:.4f}%")
    lines.append("")

    return "\n".join(lines)


def generate_normalization_h(
    center: np.ndarray,
    scale: np.ndarray,
    mu: float,
) -> str:
    """Generate normalization.h with mu-law parameters."""
    lines: list[str] = []
    lines.append("// Auto-generated by export_weights.py — do not edit by hand.")
    lines.append("// Mu-law normalization parameters (G.711 μ-law).")
    lines.append("#pragma once")
    lines.append("")

    n = len(center)
    lines.append(f"#define MU_LAW_FEATURE_DIM  {n}")
    lines.append(f"#define MU_LAW_MU           {mu:.1f}f")
    lines.append("")

    lines.append(f"static const float mu_law_center[{n}] =")
    lines.append(_array_literal(center.astype(np.float32), fmt="{:.8f}f"))
    lines.append(";")
    lines.append("")

    lines.append(f"static const float mu_law_scale[{n}] =")
    lines.append(_array_literal(scale.astype(np.float32), fmt="{:.8f}f"))
    lines.append(";")
    lines.append("")

    lines.append("// Usage:  scaled = (x[i] - mu_law_center[i]) / mu_law_scale[i];")
    lines.append("//         out[i] = copysignf(log1pf(MU_LAW_MU * fabsf(scaled)) / log1pf(MU_LAW_MU), scaled);")
    lines.append("")

    return "\n".join(lines)


# ── Main entry point ────────────────────────────────────────────────────────


def run_export(
    *,
    checkpoint_path: Path,
    output_dir: Path,
    norm_center: np.ndarray | None = None,
    norm_scale: np.ndarray | None = None,
    norm_mu: float = 255.0,
) -> dict[str, Any]:
    """Export weights and normalization params from a DenseCfC checkpoint."""
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load checkpoint
    ckpt = torch.load(str(checkpoint_path), map_location="cpu", weights_only=False)
    state_dict = ckpt["model_state_dict"]
    config = dict(ckpt["config"])

    # Verify this is the right model
    feature_order = config.get("feature_order")
    hidden_units = config.get("hidden_units")
    if feature_order != ("rms",):
        print(f"WARNING: feature_order={feature_order}, expected ('rms',)")
    if hidden_units != HIDDEN_DIM:
        print(f"WARNING: hidden_units={hidden_units}, expected {HIDDEN_DIM}")

    # 1. Generate weights.h
    print("Generating weights.h ...")
    weights_h = generate_weights_h(state_dict)
    weights_path = output_dir / "weights.h"
    weights_path.write_text(weights_h, encoding="utf-8")
    print(f"  → {weights_path} ({len(weights_h):,} bytes)")

    # 2. Generate normalization.h
    print("Computing mu-law normalization parameters ...")
    if norm_center is not None and norm_scale is not None:
        center = np.asarray(norm_center, dtype=np.float32)
        scale = np.asarray(norm_scale, dtype=np.float32)
        mu = float(norm_mu)
        print(f"  Using supplied stats: center[{len(center)}], scale[{len(scale)}], mu={mu}")
    else:
        center, scale, mu = _compute_mulaw_stats_from_data(feature_dim=INPUT_DIM)
    norm_h = generate_normalization_h(center, scale, mu)
    norm_path = output_dir / "normalization.h"
    norm_path.write_text(norm_h, encoding="utf-8")
    print(f"  → {norm_path} ({len(norm_h):,} bytes)")

    return {
        "checkpoint": str(checkpoint_path),
        "weights_h": str(weights_path),
        "normalization_h": str(norm_path),
        "feature_dim": int(len(center)),
        "mu": float(mu),
    }


def _compute_mulaw_stats_from_data(
    feature_dim: int = INPUT_DIM,
    mu: float = 255.0,
) -> tuple[np.ndarray, np.ndarray, float]:
    """Compute mu-law norm stats from S1 E2 RMS features.

    Loads raw EMG, applies bandpass + notch filtering, extracts RMS features,
    then computes per-channel mean (center) and max|deviation| (scale).

    Falls back to identity normalization if DB2 data is unavailable.
    """
    try:
        import scipy.io as sio
        import scipy.signal as signal

        db2_dir = PROJECT_ROOT / "data" / "DB2"
        if not db2_dir.exists():
            raise FileNotFoundError(f"DB2 not found at {db2_dir}")

        s1_dir = db2_dir / "DB2_s1"
        e2_files = sorted(s1_dir.glob("E2*.mat"))
        if not e2_files:
            raise FileNotFoundError("No E2 files for S1")

        # Collect RMS features across all S1 E2 recordings
        all_features: list[np.ndarray] = []
        fs = 2000.0
        window_samples = int(0.200 * fs)   # 200 ms
        stride_samples = int(0.050 * fs)   # 50 ms

        # Filter design (shared across all recordings)
        nyq = fs / 2.0
        sos_notch = signal.iirdesign(
            wp=[49.0 / nyq, 51.0 / nyq],
            ws=[49.5 / nyq, 50.5 / nyq],
            gpass=1.0, gstop=40.0,
            ftype="ellip", output="sos",
        )
        sos_bp = signal.butter(4, [20.0 / nyq, 450.0 / nyq], btype="band", output="sos")

        for fpath in e2_files[:5]:  # Use first 5 recordings for stable stats
            mat = sio.loadmat(str(fpath), simplify_cells=True)
            emg = mat.get("emg", None)
            if emg is None:
                continue
            if emg.shape[1] != feature_dim:
                print(f"  WARNING: {fpath.name} has {emg.shape[1]} channels, expected {feature_dim}")
                emg = emg[:, :feature_dim]

            # Filter
            filtered = signal.sosfilt(sos_notch, emg, axis=0)
            filtered = signal.sosfilt(sos_bp, filtered, axis=0)

            # RMS window extraction
            n_windows = (len(filtered) - window_samples) // stride_samples + 1
            if n_windows <= 0:
                continue
            rms_features = np.zeros((n_windows, feature_dim), dtype=np.float32)
            for i in range(n_windows):
                start = i * stride_samples
                window = filtered[start : start + window_samples]
                rms_features[i] = np.sqrt(np.mean(window.astype(np.float64) ** 2, axis=0))

            all_features.append(rms_features)

        if not all_features:
            raise ValueError("No valid features extracted from S1 E2")

        combined = np.concatenate(all_features, axis=0)  # (total_windows, feature_dim)
        center = combined.mean(axis=0).astype(np.float32)
        scale = np.max(np.abs(combined - center), axis=0).astype(np.float32)
        scale = np.maximum(scale, 1e-6)

        print(f"  Computed mu-law stats from {len(all_features)} S1 E2 recording(s): "
              f"{combined.shape[0]:,} windows, "
              f"center=[{center[0]:.4f}..{center[-1]:.4f}], "
              f"scale=[{scale[0]:.4f}..{scale[-1]:.4f}]")
        return center, scale, mu

    except Exception as exc:
        print(f"  WARNING: Could not compute mu-law stats from S1 E2 data ({exc})")
        print(f"  Using identity normalization (center=0, scale=1)")
        center = np.zeros(feature_dim, dtype=np.float32)
        scale = np.ones(feature_dim, dtype=np.float32)
        return center, scale, mu


# ── CLI ─────────────────────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Export DenseCfC weights as C headers")
    parser.add_argument("--checkpoint", type=Path, required=True,
                        help="Path to DenseCfC .pt checkpoint")
    parser.add_argument("--output-dir", type=Path,
                        default=Path("src/hardwareOperation"),
                        help="Output directory for C headers (default: src/hardwareOperation)")
    parser.add_argument("--norm-stats", type=Path, default=None,
                        help="Path to .npz file with 'center', 'scale', and optionally 'mu' arrays")
    args = parser.parse_args(argv)

    # Load optional norm stats
    norm_center = None
    norm_scale = None
    norm_mu = 255.0
    if args.norm_stats is not None:
        data = np.load(str(args.norm_stats))
        norm_center = data["center"]
        norm_scale = data["scale"]
        norm_mu = float(data.get("mu", 255.0))
        print(f"Loaded norm stats from {args.norm_stats}")

    report = run_export(
        checkpoint_path=args.checkpoint,
        output_dir=args.output_dir,
        norm_center=norm_center,
        norm_scale=norm_scale,
        norm_mu=norm_mu,
    )
    print(json.dumps(report, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
