// Auto-generated by export_weights.py — do not edit by hand.
// Mu-law normalization parameters (G.711 μ-law).
#pragma once

#define MU_LAW_FEATURE_DIM  12
#define MU_LAW_MU           255.0f

static const float mu_law_center[12] =
{
    0.00000000f, 0.00000000f, 0.00000000f, 0.00000000f, 0.00000000f, 0.00000000f, 0.00000000f, 0.00000000f,
    0.00000000f, 0.00000000f, 0.00000000f, 0.00000000f,
}
;

static const float mu_law_scale[12] =
{
    1.00000000f, 1.00000000f, 1.00000000f, 1.00000000f, 1.00000000f, 1.00000000f, 1.00000000f, 1.00000000f,
    1.00000000f, 1.00000000f, 1.00000000f, 1.00000000f,
}
;

// Usage:  scaled = (x[i] - mu_law_center[i]) / mu_law_scale[i];
//         out[i] = copysignf(log1pf(MU_LAW_MU * fabsf(scaled)) / log1pf(MU_LAW_MU), scaled);
